### ISSUE TITLE
哈哈

### ISSUE THREAD

**Issue by garyyiu2015** [vistazx1/flyme6_device_gemini#1]
你好幽默啊，vfy都不会改就上传了，哈哈

**Comment by vistazx1** [comment]
新手嘛。第一次做这事情。见笑。
望前辈赐教。

**Comment by vistazx1** [comment]
@garyyiu2015 
啊，好气，被笑了
第一次做patchrom 呢，还在学习中，望前辈指教。
见笑

**Comment by vistazx1** [comment]
`com.android.server.policy.PhoneWindowManager.interceptKeyBeforeQueueing(android.view.KeyEvent, int): [0x34D] register v15 has type Undefined but expected Integer`

**Comment by vistazx1** [comment]
已经开机了，继续笑吧，哈哈哈哈哈哈

**Comment by vistazx1** [comment]
vfy已解决，关闭。
